config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'top/index'
  root to: 'top#index'

  get  'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  resources :tags
  resources :favorites
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users
  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  get 'blogs/index_all'

  resources :events do
    collection do
      post :confirm
      get 'search'
    end
    resources :blogs do
      resources :comments, only: [:edit, :update, :create, :destroy]
      collection do
        post :confirm
        get 'search'
      end
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

   def initialize(user)
     if user.try(:admin?)
       can :access, :rails_admin
       can :manage, :all
     end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :content, presence: true

  mount_uploader :photo, ImageUploader

  belongs_to :user
  belongs_to :event
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :blog
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :address, :detail, :day, presence: true

  mount_uploader :image, ImageUploader
  enum planting: { "１月": 1,"２月": 2,"３月": 3,"４月": 4,"５月": 5,"６月": 6,"７月": 7,"８月": 8,"９月": 9,"１０月": 10,"１１月": 11,"１２月": 12,"未定": 13 }, _prefix: true
  enum harvest: { "１月": 1,"２月": 2,"３月": 3,"４月": 4,"５月": 5,"６月": 6,"７月": 7,"８月": 8,"９月": 9,"１０月": 10,"１１月": 11,"１２月": 12,"未定": 13 }, _prefix: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :user
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :events, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

  has_many :blogs, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :icon, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]
  def index
    if params[:select_event]
      @select_event = Event.find(params[:event_id])
      @blogs = @select_event.blogs.order(created_at: :desc)
      @name = @select_event.name
    else
      @blogs = Blog.all
    end
  end

  def index_all
    @q = Blog.ransack(params[:q])
    @blogs = @q.result.order(created_at: :desc)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to event_blogs_path(select_event: :true), notice: "ブログを投稿しました‼︎"
      else
        render :new
      end
    end
  end

  def show
    @comment = Comment.new
    @comments = @blog.comments.includes(:user)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to event_blogs_path(select_event: :true), notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to event_blogs_path(select_event: :true), notice:"ブログを削除しました！"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def search
    @results = @q.result
  end

  private

  def  blog_params
    params.require(:blog).permit(:title, :content, :photo, :photo_cache).merge(event_id: params[:event_id])
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def set_q
    @q = Blog.ransack(params[:q])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit_blog
    if action_name == 'new' || action_name == 'create'
      confirm_event_blogs_path
    elsif action_name == 'edit'
      event_blog_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def choose_new_or_edit
  if action_name == 'new' || action_name == 'create'
    confirm_events_path
  elsif action_name == 'edit'
    event_path
  end
end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<div class="main">
  <%= form_with(model: [:event,@blog] ,local: true ,url: choose_new_or_edit_blog ) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @blog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="blog_content">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
    <div class="blog_photo">
      <%= form.label :photo %>
      <%= image_tag(@blog.photo.url) if @blog.photo && @blog.photo.url %><br>
      <%= form.file_field :photo %>
      <%= form.hidden_field :photo_cache %>
    </div>
      <%= form.hidden_field :event_id %>
    <div class="text-center">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
  <div class="text-center">
    <%= link_to "戻る", :back %>
  </div>
</div>

app/views/blogs/confirm.html.erb
<div class="text-center">
  <h3>以下の内容で、送信する。</h3>
</div>
<%= form_with(model: @blog, url: event_blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :photo %>
  <%= form.hidden_field :photo_cache %>
  <%= form.hidden_field :event_id %>
<div class="main">
  <p>タイトル:<%= @blog.title %></p>
  <p>内容:<%= @blog.content %></p>
</div>
<div class="text-center">
  <%= image_tag(@blog.photo.url) if @blog.photo && @blog.photo.url %>
</div>
<div class="text-center">
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
</div>  
<% end %>

app/views/blogs/edit.html.erb
<div class="text-center">
  <h2>ブログを編集する</h2>
</div>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1><%= @name %>のブログ一覧</h1>

<%= search_form_for @q, url: search_event_blogs_path do |f| %>
  <%= f.search_field :title_or_content_cont, placeholder: '内容' %>
  <%= f.search_field :user_name_cont, placeholder: '作者' %>
  <br>
  <%= f.submit '検索' %>
<% end %>

<% @blogs.each do |blog| %>
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <%= link_to image_tag(blog.photo.url),event_blog_path(blog.event.id, blog.id) %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= blog.title %></h5>
        <p class="card-text"><%=blog.content%></p>
      </div>
      <div class="card-footer">
        <p class="card-text"><%= link_to blog.user.name,user_path(blog.user)%><small class="text-muted">  <%=blog.created_at.strftime('%Y/%m/%d') %></small></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/blogs/index_all.html.erb
<h1>ブログ一覧</h1>
<%= search_form_for @q, url: blogs_index_all_path do |f| %>
  <%= f.search_field :title_or_content_cont, placeholder: '内容' %>
  <%= f.search_field :user_name_cont, placeholder: '作者' %>
  <br>
  <%= f.submit '検索' %>
<% end %>
<% @blogs.each do |blog| %>
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <%= link_to image_tag(blog.photo.url,size: '275x183'),event_blog_path(blog.event.id, blog.id) %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= blog.title %></h5>
        <p class="card-text"><%=blog.content%></p>
      </div>
      <div class="card-footer">
        <p class="card-text"><%= link_to blog.user.name,user_path(blog.user)%><small class="text-muted">  <%=blog.created_at.strftime('%Y/%m/%d') %></small></p>
      </div>
    </div>
  </div>
</div>
<% end %>
<!-- <div class="container">
  <div class="row">
    <% @blogs.each do |blog| %>
     -->
    <!-- <div class="col-md-3">
  <div class="row g-0">
    <div class="col-md-4">
      <%= link_to image_tag(blog.photo.url),event_blog_path(blog.event.id, blog.id) %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= blog.title %></h5>
        <p class="card-text"><%=blog.content%></p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>

    </div>
  </div>
</div>
<% end %>
</div>
</div> -->

<!-- <table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>作者</th>
    <th>写真</th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= blog.user.name %></td>
    <td><%= link_to image_tag(blog.photo.url),event_blog_path(blog.event.id, blog.id) %></td>
  </tr>
<% end %>
</table> -->

app/views/blogs/new.html.erb
<div class="text-center">
  <h2>ブログを登録する</h2>
</div>

<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="text-center">
  <h1>ブログ内容画面</h1>
</div>
<div class="main">
  <p>タイトル:<%= @blog.title %></p>
  <p>内容:<%= @blog.content %></p>
  <p>作者:<%= @blog.user.name %></p>
  <p>写真: <%= image_tag @blog.photo.url %></p>
</div>
<div class="text-center">
  <h3>コメント一覧</h3>
    <table class="table">
      <tr>
        <th>投稿者</th>
        <th>内容</th>
      </tr>
    <% @comments.each do |c| %>
      <tr>
        <td><%= c.user.name %></td>
        <td><%= c.content %></td>
        <% if user_signed_in? %>
          <% if current_user.id == c.user_id %>
            <td><%= link_to "編集", edit_event_blog_comment_path(c, event_id: params[:event_id],blog_id: @blog) %></td>
            <td><%= link_to "削除", event_blog_comment_path(c, event_id: params[:event_id],blog_id: @blog), method: :delete %></td>
          <% elsif current_user.id == @blog.user_id then %>
            <td><%= link_to "削除", event_blog_comment_path(c, event_id: params[:event_id],blog_id: @blog), method: :delete %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<div class="text-center">

  <% if user_signed_in? %>
    <%= form_with model: [@blog.event, @blog, @comment] do |f| %>
      <%= f.text_area :content, placeholder: "コメントする" %>
      <%= f.submit "登録" %>
    <% end %>
  <% end %>

<%= link_to "一覧画面にもどる", :back %>
</div>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>