config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'top/index'
  root to: 'top#index'

  get  'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  resources :tags
  resources :favorites
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users
  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  get 'blogs/index_all'

  resources :events do
    collection do
      post :confirm
      get 'search'
    end
    resources :blogs do
      resources :comments, only: [:edit, :update, :create, :destroy]
      collection do
        post :confirm
        get 'search'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :blogs, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :icon, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  protected
    def after_inactive_sign_up_path_for(resource)
       events_path
    end

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    def after_update_path_for(resource)
      user_profile_path(current_user)
    end


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% if params[:id].nil? || @user.id == current_user.id %>
  <h1>ようこそ<%= current_user.name %>さん</h1>
  <p>アイコン：<%= image_tag current_user.icon.url %></p><br>
  <p>登録email：<%= current_user.email %></p>

  <%= link_to 'お気に入り一覧', favorites_path %><br>
  <%= link_to "アカウントを編集", edit_user_registration_path %><br>


<h1><%= current_user.name %>さんのイベント一覧</h1>

  <div class="container">
    <div class="row">
      <% @user.events.each do |event| %>
        <div class="col-md-4 p-1">
          <div class="card h-100">
            <%= link_to image_tag(event.image.url, class: "card-img-top"), event_path(event.id) %>
            <div class="card-body text-center">
              <h4 class="card-title"><%=event.name %></h4>
              <p class="card-text"><%=event.detail %></p>
              <p class="card-text">開催者：<%= link_to event.user.name,user_path(event.user)%></p>
              <p class="card-text">開催日<%=event.day %></p>
              <%= link_to "確認",event_path(event.id) %>
              <%= link_to "編集", edit_event_path(event.id) %>
              <%= link_to '削除', event_path(event.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
            </div>
            <div class="card-footer text-center">
              <small class="text-muted">最終更新<%= event.updated_at.strftime('%Y/%m/%d') %></small>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>

<h1><%= current_user.name %>さんのブログ一覧</h1>
<% @user.blogs.each do |blog| %>
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <%= link_to image_tag(blog.photo.url,size: '275x183'),event_blog_path(blog.event.id, blog.id) %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= blog.title %></h5>
        <p class="card-text"><%=blog.content%></p>
        <p class="card-text"><%= link_to blog.user.name,user_path(blog.user)%><small class="text-muted">  <%=blog.created_at.strftime('%Y/%m/%d') %></small></p>
        <%= link_to "内容を確認する",event_blog_path(blog.event.id, blog.id) %>
        <%= link_to "ブログを編集する", edit_event_blog_path(blog.event.id,blog.id) %>
        <%= link_to 'ブログを削除する', event_blog_path(blog.event.id,blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
      </div>
    </div>
  </div>
</div>
<% end %>


<% else %>
  <h2>ここは<%= @user.name %>さんのページです</h2>
  <p>アイコン：<%= image_tag @user.icon.url %></p>

  <p><%= mail_to @user.email, "#{@user.name}さんに問い合わせをする", :encode => 'hex' %></p>

  <h1><%= @user.name %>さんのイベント一覧</h1>
  <div class="container">
    <div class="row">
      <% @user.events.each do |event| %>
        <div class="col-md-4 p-1">
          <div class="card h-100">
            <%= link_to image_tag(event.image.url, class: "card-img-top"), event_path(event.id) %>
            <div class="card-body text-center">
              <h4 class="card-title"><%=event.name %></h4>
              <p class="card-text"><%=event.detail %></p>
              <p class="card-text">開催者：<%= link_to event.user.name,user_path(event.user)%></p>
              <p class="card-text">開催日<%=event.day %></p>
            </div>
            <div class="card-footer text-center">
              <small class="text-muted">最終更新<%= event.updated_at.strftime('%Y/%m/%d') %></small>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>

  <h1><%= @user.name %>さんのブログ一覧</h1>
  <% @user.blogs.each do |blog| %>
    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-4">
          <%= link_to image_tag(blog.photo.url,size: '275x183'),event_blog_path(blog.event.id, blog.id) %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= blog.title %></h5>
            <p class="card-text"><%=blog.content%></p>
            <p class="card-text"><%= link_to blog.user.name,user_path(blog.user)%><small class="text-muted">  <%=blog.created_at.strftime('%Y/%m/%d') %></small></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>