config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'top/index'
  root to: 'top#index'

  get  'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  resources :tags
  resources :favorites
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users
  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  get 'blogs/index_all'

  resources :events do
    collection do
      post :confirm
      get 'search'
    end
    resources :blogs do
      resources :comments, only: [:edit, :update, :create, :destroy]
      collection do
        post :confirm
        get 'search'
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :address, :detail, :day, presence: true

  mount_uploader :image, ImageUploader
  enum planting: { "１月": 1,"２月": 2,"３月": 3,"４月": 4,"５月": 5,"６月": 6,"７月": 7,"８月": 8,"９月": 9,"１０月": 10,"１１月": 11,"１２月": 12,"未定": 13 }, _prefix: true
  enum harvest: { "１月": 1,"２月": 2,"３月": 3,"４月": 4,"５月": 5,"６月": 6,"７月": 7,"８月": 8,"９月": 9,"１０月": 10,"１１月": 11,"１２月": 12,"未定": 13 }, _prefix: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :user
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_q

def index
  # @tags = Tag.all
  @events = @q.result(distinct: true).order(created_at: :desc)
end

def new
  @event = Event.new
end

def create
  @event = current_user.events.build(event_params)
  if params[:back]
    render :new
  else
    if @event.save
      redirect_to events_path, notice: "イベントを作成しました！"
    else
      render :new
    end
  end
end

def show
  @favorite = current_user.favorites.find_by(event_id: @event.id)
end

def edit
end

def update
  if @event.update(event_params)
    redirect_to events_path, notice: "イベントを編集しました！"
  else
    render :edit
  end
end

def destroy
  @event.destroy
  redirect_to events_path, notice:"イベントを削除しました！"
end

def confirm
  @event = current_user.events.build(event_params)
  render :new if @event.invalid?
end

def search
  @results = @q.result
end


private

def event_params
  params.require(:event).permit(:name, :address, :latitude, :longitude, :day, :remork,
                                :detail, :planting, :harvest, :crop, :image, :image_cache, { tag_ids: [] })
end

def set_event
  @event = Event.find(params[:id])
end

def set_q
  @q = Event.ransack(params[:q])
end
end

app/helpers/events_helper.rb
module EventsHelper
  def choose_new_or_edit
  if action_name == 'new' || action_name == 'create'
    confirm_events_path
  elsif action_name == 'edit'
    event_path
  end
end
end

app/views/events/_form.html.erb
<div class="main">
<%= form_with(model: @event, local: true ,url: choose_new_or_edit  ) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= @event.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="event_name">
    <%= form.label :イベント名 %>
    <%= form.text_field :name %>
  </div>
  <div class="event_day">
    <%= form.label :開催日 %>
    <%= form.date_field :day %>
  </div>
  <div class="event_address">
    <%= form.label :住所 %>
    <%= form.text_field :address, autofocus: true  %>
  </div>
  <div class="event_detail">
    <%= form.label :内容 %>
    <%= form.text_area :detail %>
  </div>
  <div class="event_planting">
    <%= form.label :植え付け %>
    <%= form.select :planting, Event.plantings.keys.to_a, { include_blank:'未選択可能'} %>
  </div>
  <div class="event_harvest">
    <%= form.label :収穫 %>
    <%= form.select :harvest, Event.harvests.keys.to_a, { include_blank:'未選択可能'} %>
  </div>
  <div class="event_crop">
    <%= form.label :作物 %>
    <%= form.text_field :crop %>
  </div>
  <div class="event_tag">
    <%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) %>
  </div>
  <div class="event_remork">
    <%= form.label :備考 %>
    <%= form.text_area :remork %>
  </div>
  <div class="event_image">
    <%= form.label :イメージ %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="text-center">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>
<div class="text-center">
<%= link_to "戻る", :back %>
</div>
</div>

app/views/events/confirm.html.erb
<div class="text-center">
  <h3>以下の内容で、送信する。</h3>
</div>
<%= form_with(model: @event, url: events_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :detail %>
  <%= form.hidden_field :address %>
  <%= form.hidden_field :crop %>
  <%= form.hidden_field :remork %>
  <%= form.hidden_field :planting %>
  <%= form.hidden_field :harvest %>
  <%= form.hidden_field :day %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :latitude %>
  <%= form.hidden_field :longitude %>
  <% @event.tag_ids.each do |tag_ids| %>
    <%= form.hidden_field :tag_ids, multiple: true, value: tag_ids %>
  <% end %>

  <div class="main">

  <p>名前:<%= @event.name %></p>
  <p>開催日:<%= @event.day %></p>
  <p>住所:<%= @event.address %></p>
  <p>詳細:<%= @event.detail %></p>
  <p>植え付け月:<%= @event.planting %></p>
  <p>収穫月:<%= @event.harvest %></p>
  <p>作物:<%= @event.crop %></p>
  <p>その他:<% @event.tags.each do |tag| %>
                <%= tag.name %>
              <% end %></p>
  <p>備考:<%= @event.remork %></p>
  </div>
  <div class="text-center">
  <%= image_tag(@event.image.url) if @event.image && @event.image.url %>
  </div>
  <div class="text-center">
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="text-center">
  <h2>イベントを編集する</h2>
</div>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>イベント一覧</h1>
<%= link_to '新しくイベントを登録する', new_event_path %>

<%= search_form_for @q do |f| %>
  <%= f.search_field :detail_or_remork_or_name_or_address_or_crop_cont, placeholder: '内容'%>
  <%= f.search_field :user_name_cont, placeholder: '開催者'%>
  <%= f.select :planting_eq, [['１月', 1], ['２月', 2], ['３月', 3],['４月',4], ['５月', 5], ['６月', 6],['７月', 7], ['８月', 8],  ['９月', 9], ['１０月', 10],['１１月', 11], ['１２月', 12], ['未定', 13]],{include_blank: '植え付け'} %>
  <%= f.select :harvest_eq, [['１月', 1], ['２月', 2], ['３月', 3],['４月',4], ['５月', 5], ['６月', 6],['７月', 7], ['８月', 8],  ['９月', 9], ['１０月', 10],['１１月', 11], ['１２月', 12], ['未定', 13]],{include_blank: '収穫'} %>
  <%= f.date_field :day_gteq%>
   <span>~</span>
  <%= f.date_field :day_lteq%><br>
  <% Tag.all.each do |tag| %>
    <%= f.check_box :tags_id_eq_any, { multiple: true, checked: tag[:checked], disabled: tag[:disabled], include_hidden: false }, tag[:id] %>
    <%= tag.name %>
  <% end %>
  <%= f.submit '検索' %>
<% end %>

<div class="container">
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-md-4 p-1">
        <div class="card h-100">
          <%= link_to image_tag(event.image.url, class: "card-img-top"), event_path(event.id) %>
          <div class="card-body text-center">
            <h4 class="card-title"><%=event.name %></h4>
            <p class="card-text"><%=event.detail %></p>
            <p class="card-text">開催者：<%= link_to event.user.name,user_path(event.user)%></p>
            <p class="card-text">開催日<%=event.day %></p>
          </div>
          <div class="card-footer text-center">
            <small class="text-muted">最終更新<%= event.updated_at.strftime('%Y/%m/%d') %></small>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/events/new.html.erb
<div class="text-center">
  <h2>イベントを登録する</h2>
</div>
<%= render 'form' %>

app/views/events/show.html.erb
<div class="main">
  <div class="text-center">
  <h1>イベント内容画面</h1>

<% unless @event.user_id == current_user.id %>
  <%= mail_to @event.user.email, "#{@event.user.name}さんに問い合わせをする", :encode => 'hex' %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(event_id: @event.id), method: :post %>
  <% end %>
<% end %><br>

<%= link_to 'このイベントにブログを登録する', new_event_blog_path(@event) %>
<%= link_to 'このイベントのブログを見る', event_blogs_path(@event, select_event: :true) %>
</div>
<p>名前:<%= @event.name %></p>
<p>開催日:<%= @event.day %></p>
<p>住所:<%= @event.address %></p>
<p>詳細:<%= @event.detail %></p>
<p>植え付け月:<%= @event.planting %></p>
<p>収穫月:<%= @event.harvest %></p>
<p>作物:<%= @event.crop %></p>
<p>その他:<% @event.tags.each do |tag| %>
              <%= tag.name %>
            <% end %></p>
<p>備考:<%= @event.remork %></p>
<p>開催者:<%= @event.user.name %></p>
<p>イメージ: <%= image_tag @event.image.url %></p>

<script type="text/javascript">
     function initMap() {
       var test = {lat: <%= @event.latitude %>, lng: <%= @event.longitude %>};
       var map = new google.maps.Map(document.getElementById('map'), {
                 zoom: 15,
                 center: test
                 });
       var transitLayer = new google.maps.TransitLayer();
       transitLayer.setMap(map);
       var contentString = '住所：<%= @event.address %>';
       var infowindow = new google.maps.InfoWindow({
         content: contentString
       });
       var marker = new google.maps.Marker({
                     position:test,
                     map: map,
                     title: contentString
                   });
       marker.addListener('click', function() {
         infowindow.open(map, marker);
       });
     }
   </script>
   <script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
   </script>
   <style type="text/css">
     #map { height: 400px;
           width: 90%;}
   </style>
   <div id="map"></div>
   </div>

   <%= link_to "一覧画面にもどる", events_path %>