config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'top/index'
  root to: 'top#index'

  get  'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  resources :tags
  resources :favorites
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users
  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  get 'blogs/index_all'

  resources :events do
    collection do
      post :confirm
      get 'search'
    end
    resources :blogs do
      resources :comments, only: [:edit, :update, :create, :destroy]
      collection do
        post :confirm
        get 'search'
      end
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

   def initialize(user)
     if user.try(:admin?)
       can :access, :rails_admin
       can :manage, :all
     end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :content, presence: true

  mount_uploader :photo, ImageUploader

  belongs_to :user
  belongs_to :event
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :blog
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :address, :detail, :day, presence: true

  mount_uploader :image, ImageUploader
  enum planting: { "１月": 1,"２月": 2,"３月": 3,"４月": 4,"５月": 5,"６月": 6,"７月": 7,"８月": 8,"９月": 9,"１０月": 10,"１１月": 11,"１２月": 12,"未定": 13 }, _prefix: true
  enum harvest: { "１月": 1,"２月": 2,"３月": 3,"４月": 4,"５月": 5,"６月": 6,"７月": 7,"８月": 8,"９月": 9,"１０月": 10,"１１月": 11,"１２月": 12,"未定": 13 }, _prefix: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :user
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :events, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

  has_many :blogs, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :icon, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit_blog
    if action_name == 'new' || action_name == 'create'
      confirm_event_blogs_path
    elsif action_name == 'edit'
      event_blog_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def choose_new_or_edit
  if action_name == 'new' || action_name == 'create'
    confirm_events_path
  elsif action_name == 'edit'
    event_path
  end
end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>OrtoMio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-success sticky-top">
      <div class="container-fluid">
        <%= link_to image_tag("logo.png",size: '80x60',class: "navbar-brand"), top_index_path %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
               <%= link_to "TOP",top_index_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "お問い合わせ",inquiry_path , class: "nav-link" %>
              </li>
            <% if current_user.try(:admin?) %>
              <li class="nav-item">
                <%= link_to "管理画面へ",rails_admin_path,class: "nav-link" %>
              </li>
            <% end %>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", user_path(current_user.id),class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path,class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
              <li class="nav-item">
              <%= link_to "イベント", events_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ブログ", blogs_index_all_path, class: "nav-link" %>
              </li>
          </ul>
        </div>
      </div>
    </nav>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>

      <%= yield %>

    <footer class="footer fixed-bottom　mt-4 py-3 bg-light">
      <div class="container text-center">
        <span class="text-muted">Demo Company &copy; All Right Reserved.</span>
      </div>
    </footer>

  </body>
</html>